env:
  node: true
  es2021: true
  browser: true

extends: eslint:recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  no-unused-vars: warn
  no-empty: [error, { allowEmptyCatch: true }]
  func-style: [error, declaration, { allowArrowFunctions: true }]
  quotes: [error, single, { avoidEscape: true }]
  semi: [error, always]
  indent: [error, 2, { SwitchCase: 1 }]
  comma-dangle: [error, always-multiline]
  arrow-parens: [error, always]
  eol-last: [error, always]
  no-multiple-empty-lines: [error, { max: 1 }]
  curly: [error, multi-line]

ignorePatterns: [dist/, node_modules/]
